import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faPhone,
  faEnvelope,
  faMapMarkerAlt,
  faClock,
  faBars,
  faTimes,
  faChevronDown,
  faChevronRight,
  faArrowUp,
  faArrowRight,
  faCheck,
  faStar,
  faShieldAlt,
  faCertificate,
  faIndustry,
  faTools,
  faLeaf,
  faBolt,
  faWifi,
  faFireAlt,
  faThLarge,
  faPaperPlane,
  faUser,
  faBuilding,
  faDownload,
  faExternalLinkAlt,
} from "@fortawesome/free-solid-svg-icons";
import {
  faFacebook,
  faTwitter,
  faInstagram,
  faLinkedin,
  faYoutube,
  faWhatsapp,
} from "@fortawesome/free-brands-svg-icons";

// Register all icons in the FA library (needed for server components)
library.add(
  faPhone,
  faEnvelope,
  faMapMarkerAlt,
  faClock,
  faBars,
  faTimes,
  faChevronDown,
  faChevronRight,
  faArrowUp,
  faArrowRight,
  faCheck,
  faStar,
  faShieldAlt,
  faCertificate,
  faIndustry,
  faTools,
  faLeaf,
  faBolt,
  faWifi,
  faFireAlt,
  faThLarge,
  faPaperPlane,
  faUser,
  faBuilding,
  faDownload,
  faExternalLinkAlt,
  faFacebook,
  faTwitter,
  faInstagram,
  faLinkedin,
  faYoutube,
  faWhatsapp
);

export const icons = {
  // Contact
  phone: faPhone,
  email: faEnvelope,
  location: faMapMarkerAlt,
  clock: faClock,
  // UI
  menu: faBars,
  close: faTimes,
  chevronDown: faChevronDown,
  chevronRight: faChevronRight,
  arrowUp: faArrowUp,
  arrowRight: faArrowRight,
  check: faCheck,
  star: faStar,
  download: faDownload,
  externalLink: faExternalLinkAlt,
  // Features
  shield: faShieldAlt,
  certificate: faCertificate,
  industry: faIndustry,
  tools: faTools,
  leaf: faLeaf,
  bolt: faBolt,
  wifi: faWifi,
  fire: faFireAlt,
  grid: faThLarge,
  send: faPaperPlane,
  user: faUser,
  building: faBuilding,
  // Social
  facebook: faFacebook,
  twitter: faTwitter,
  instagram: faInstagram,
  linkedin: faLinkedin,
  youtube: faYoutube,
  whatsapp: faWhatsapp,
} as const;
